substitutions:
  ###### CHANGE ME START ######
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: alnor
  friendly_name: Alnor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "ynnVkN2QUH9MQC9RQ/PwitDfWpvpR+gkNfcuYzQ2uuI="

ota:
  - platform: esphome
    password: "128cd8f447f53032ed69f882f7198fb0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Alnor Fallback Hotspot"
    password: "Rudy1023!"

captive_portal:


uart:
  tx_pin: GPIO26
  rx_pin: GPIO27
  baud_rate: 9600

modbus_controller:
- id: modbus_device
  address: 0x1   ## address of the Modbus slave device on the bus
  setup_priority: -10

sensor:
##modbus addresses  (hidden/internal)
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Modbus address"  ##RW?
  skip_updates: 15
  internal: true ##rem to show
  id: modbus_address
  register_type: holding ## Modbus funcion #3
  address: 101    ## address of the register inside the Modbus slave device
  value_type: U_WORD
  filters:
  - multiply: 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  skip_updates: 15
  name: "Panel address"  ##RW?
  internal: true ##rem to show
  id: panel_modbus_address
  register_type: holding ## Modbus funcion #3
  address: 101    ## address of the register inside the Modbus slave device
  value_type: U_WORD
  filters:
  - multiply: 1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Alarm code"
  id: alarm_code
  icon: "mdi:alert"
  register_type: holding
  address: 25    ## address of the register inside the Modbus slave device
  value_type: U_WORD

##fans
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Speed of supply fan"
  register_type: holding
  address: 6    ## address of the register inside the Modbus slave device
  unit_of_measurement: "rpm"
  value_type: U_WORD
  icon: "mdi:fan-chevron-up"
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Speed of exhaust fan"
  register_type: holding
  address: 7    ## address of the register inside the Modbus slave device
  unit_of_measurement: "rpm"
  value_type: S_WORD  
  icon: "mdi:fan-chevron-down"

##temperatures
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Temperature OA (Outdoor air)"
  icon: "mdi:thermometer-chevron-up"
  id: TerOA
  register_type: holding  ## Modbus funcion #3
  address: 11    ## address of the register inside the Modbus slave device
  device_class: temperature
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  value_type: S_WORD  
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: TerRA
  name: "Temperature RA (Return air)"
  icon: "mdi:thermometer-chevron-down"
  register_type: holding ## Modbus funcion #3
  device_class: temperature
  address: 12  
  unit_of_measurement: "°C"
  value_type: S_WORD  
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Temperature SA (Supply air)"
  skip_updates: 5
  ##internal: True ## -100 C ? what is this?
  id: TerSA
  register_type: holding ## Modbus funcion #3
  device_class: temperature
  address: 13    
  unit_of_measurement: "°C"
  value_type: S_WORD  
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: TerP  ## -40 +80
  name: "Panel temperature" ##RW
  skip_updates: 5
  register_type: holding  ## Modbus funcion #3
  address: 14    
  device_class: temperature
  unit_of_measurement: "°C"
  value_type: S_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: sensor1
  name: "Sensor 1"
  skip_updates: 5
  register_type: holding  ## Modbus funcion #3
  address: 15
  device_class: humidity
  unit_of_measurement: "%"
  value_type: S_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.01
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: sensor2
  name: "Sensor 2"
  skip_updates: 5
  register_type: holding  ## Modbus funcion #3
  address: 15
  device_class: humidity
  unit_of_measurement: "%"
  value_type: S_WORD
  accuracy_decimals: 1
  filters:
  - multiply: 0.01

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "DX running mode"  ##RW?
  #internal: true ##rem to show
  id: dx_running_mode
  register_type: holding ## Modbus funcion #3
  address: 89   
  value_type: U_WORD
  filters:
  - multiply: 1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "version" 
  id: program_version
  register_type: holding ## Modbus funcion #3
  address: 0
  value_type: U_WORD


number:
#- platform: modbus_controller
#  modbus_controller_id: modbus_device
#  id: unit_on_off
#  address: 1    
#  register_type: holding
#  name: "Unit on/off"
#  icon: "mdi:fan"
#  min_value: 0
#  max_value: 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: temperature_set_point
  name: "Temperature set point"  ##RW
  skip_updates: 5
  register_type: holding  ## Modbus funcion #3
  address: 56   
  device_class: temperature
  unit_of_measurement: "°C"
  value_type: S_WORD
  min_value: 18
  max_value: 28

select:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: unit_on_off
  address: 1    
  name: "Unit on/off"
  icon: "mdi:fan"
  optionsmap:
      "off": 0
      "on": 1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "rotor" 
  id: rotor
  address: 36
  optionsmap:
      "off": 0
      "on": 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "By-pass status"
  icon: "mdi:swap-horizontal"
  id: bypass_status
  address: 37    
  optionsmap:
      "off": 0
      "on": 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "preheat" 
  id: preheat
  icon: "mdi:heat-wave"
  address: 38
  optionsmap:
      "off": 0
      "on": 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "heat 1" 
  id: heat1
  icon: "mdi:heat-wave"
  address: 39
  optionsmap:
      "off": 0
      "on": 1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "heat 2" 
  icon: "mdi:heat-wave"
  id: heat2
  address: 40
  optionsmap:
      "off": 0
      "on": 1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: supply_fan_velocity_stage
  address: 52    
  name: "Fan supply velocity stage"  ##RW?
  icon: "mdi:fan-chevron-up"
  optionsmap:
      "Low": 0
      "Med": 1
      "High": 2
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: exhaust_fan_velocity_stage
  address: 53    
  name: "Fan exhaust velocity stage"  ##RW?
  icon: "mdi:fan-chevron-down"
  optionsmap:
      "Low": 0
      "Med": 1
      "High": 2
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: mode_selection
  address: 50    
  name: "Mode selection"
  icon: "mdi:fan-auto"
  optionsmap:
      "> Standard >": 0
      "Only exhaust fan >": 1
      "> Only supply fan": 2
      "(VOD)": 3
